/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/kamelet-source/pkg/apis/samples/v1alpha1"
)

// FakeKameletSources implements KameletSourceInterface
type FakeKameletSources struct {
	Fake *FakeSamplesV1alpha1
	ns   string
}

var kameletsourcesResource = v1alpha1.SchemeGroupVersion.WithResource("kameletsources")

var kameletsourcesKind = v1alpha1.SchemeGroupVersion.WithKind("KameletSource")

// Get takes name of the kameletSource, and returns the corresponding kameletSource object, and an error if there is any.
func (c *FakeKameletSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KameletSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kameletsourcesResource, c.ns, name), &v1alpha1.KameletSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KameletSource), err
}

// List takes label and field selectors, and returns the list of KameletSources that match those selectors.
func (c *FakeKameletSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KameletSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kameletsourcesResource, kameletsourcesKind, c.ns, opts), &v1alpha1.KameletSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KameletSourceList{ListMeta: obj.(*v1alpha1.KameletSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.KameletSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kameletSources.
func (c *FakeKameletSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kameletsourcesResource, c.ns, opts))

}

// Create takes the representation of a kameletSource and creates it.  Returns the server's representation of the kameletSource, and an error, if there is any.
func (c *FakeKameletSources) Create(ctx context.Context, kameletSource *v1alpha1.KameletSource, opts v1.CreateOptions) (result *v1alpha1.KameletSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kameletsourcesResource, c.ns, kameletSource), &v1alpha1.KameletSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KameletSource), err
}

// Update takes the representation of a kameletSource and updates it. Returns the server's representation of the kameletSource, and an error, if there is any.
func (c *FakeKameletSources) Update(ctx context.Context, kameletSource *v1alpha1.KameletSource, opts v1.UpdateOptions) (result *v1alpha1.KameletSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kameletsourcesResource, c.ns, kameletSource), &v1alpha1.KameletSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KameletSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKameletSources) UpdateStatus(ctx context.Context, kameletSource *v1alpha1.KameletSource, opts v1.UpdateOptions) (*v1alpha1.KameletSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kameletsourcesResource, "status", c.ns, kameletSource), &v1alpha1.KameletSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KameletSource), err
}

// Delete takes name of the kameletSource and deletes it. Returns an error if one occurs.
func (c *FakeKameletSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kameletsourcesResource, c.ns, name, opts), &v1alpha1.KameletSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKameletSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kameletsourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KameletSourceList{})
	return err
}

// Patch applies the patch and returns the patched kameletSource.
func (c *FakeKameletSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KameletSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kameletsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.KameletSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KameletSource), err
}
